import type { Metadata } from 'next';

import './globals.css';

import Provider from '@/components/provider/Provider';
import { StyledComponentsRegistry } from '@/libs/AntdRegistry';

export const metadata: Metadata = {
   title: 'Todo list',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <StyledComponentsRegistry>
         <html lang='en'>
            <body suppressHydrationWarning={true} className='bg-[#B4D4FF]'>
               <Provider>
                  <div className='xl:pb-12 xl:pt-6 p-4 min-h-screen flex'>
                     {children}
                  </div>
               </Provider>
            </body>
         </html>
      </StyledComponentsRegistry>
   );
}
