import type { Metadata } from 'next';

import './globals.css';

import { StyledComponentsRegistry } from '@/libs/AntdRegistry';

export const metadata: Metadata = {
   title: 'Todolist',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <StyledComponentsRegistry>
         <html lang='en'>
            <body suppressHydrationWarning={true}>
               <div className='py-4'>{children}</div>
            </body>
         </html>
      </StyledComponentsRegistry>
   );
}
