import type { Metadata } from 'next';

import './globals.css';

import AuthProvider from '@/components/provider/AuthProvider';
import { StyledComponentsRegistry } from '@/libs/AntdRegistry';
import ThemeProvider from '@/components/provider/ThemeProvider';

export const metadata: Metadata = {
   title: 'Todo list',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <StyledComponentsRegistry>
         <html lang='en'>
            <body
               suppressHydrationWarning={true}
               className='bg-[#B4D4FF] dark:bg-[#030637]'
            >
               <AuthProvider>
                  <ThemeProvider>
                     <div className='xl:pb-12 xl:pt-6 min-h-screen flex'>
                        {children}
                     </div>
                  </ThemeProvider>
               </AuthProvider>
            </body>
         </html>
      </StyledComponentsRegistry>
   );
}
